name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ProbeZS Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate Parameter Name Mappings
        run: |
          ./gradlew setupDecompWorkspace
          ./gradlew generateParameterNameMappings
      - name: Upload Parameter Name Mappings
        uses: actions/upload-artifact@v3
        with:
          name: mappings
          path: generated
      - name: Copy Parameter Name Mappings to Sources
        run: cp -f ./generated/method-parameter-names.yaml ./src/main/resources/mappings/
      - name: Build with Gradle
        run: ./gradlew build
      - name: Get gradle version
        uses: thecodemonkey/action-get-gradle-version@master
        id: version
        with:
          file: gradle.properties
      - name: Get Current Time
        id: time
        run: echo "NOW=$(date + '%Y%m%dT%H%M%S')" >> "$GITHUB_OUTPUT"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.version.outputs.version }}-${{ steps.time.outputs.NOW }}
          files: ./build/libs/ProbeZS-${{ steps.version.outputs.version }}.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Github Pages Repository
        uses: actions/checkout@v3
        with:
          repository: friendlyhj/friendlyhj.github.io
          token: ${{ secrets.PAGE_TOKEN }}
      - name: Download the Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: mappings
      - name: Move Mappings to Pages Repository
        run: cp -f $GITHUB_WORKSPACE/generated/* $GITHUB_WORKSPACE/probezs-mappings
      - name: Commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          author_name: friendlyhj
          author_email: youyi580@qq.com
          message: Update ProbeZS Parameter Name Mappings
