name: Submodule Updates

on:
  schedule:
    - cron: '0 8 * * 2,4,6,0'
  workflow_dispatch:

jobs:
  build:
    name: Submodule update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ProbeZS Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAGE_TOKEN }}
      - name: Update Submodules
        run: git submodule update --remote
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: friendlyhj
          author_email: youyi580@qq.com
          message: Update Submodules
